language: python
python:
  - "3.4"

install:
  - pip install -Ur requirements.txt
  - pip install -Ur requirements-tests.txt

env:
  - PYTHONPATH="$TRAVIS_BUILD_DIR/src"

before_script:
  - source misc/pylint_files

script:
  # run pylint with no reports
  - pylint -r n $PYLINT_FILES
  - py.test
